<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MichMapper</AssemblyName>
    <RootNamespace>MichMapper</RootNamespace>
    <Version>3.19.0</Version>
    <Product>Mich Mapper</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.12" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
  </ItemGroup>
</Project>
